export const RickyismsList = [
  "A link is only as long as your longest strong chain",
  "All for all and one for one",
  "Al-I-Ga-tor",
  "Alright, Heisenstein",
  "Astronaut Cock & Snoopy The Fuck Dog",
  "Atodaso (possibly \"a toe to sew\")",
  "Avengers of the Nerds",
  "Awkwardly Situation",
  "Bagmitten",
  "Bee Suave",
  "Brain Phones",
  "Beauty is in the eye when you hold her",
  "Bottle of joy",
  "Book Learning",
  "Breakfast at bed",
  "Burn the hatchet at both ends",
  "Brain Compartments and Brain Departments",
  "Can you give me a bit of credjudice?",
  "Carbonator",
  "Catch 23 situation",
  "CDR",
  "Cherry Trees",
  "Child Reports",
  "Church of Later Day Saints",
  "Civilian War",
  "Looks like a tropical earthquake blew through here",
  "Cock-a-doodle Fucking Ketchup Chips",
  "Come to turns with it",
  "Crop of Shit",
  "Crystally-clear",
  "Cubic Zarcarbian",
  "Decnals",
  "Delicately situation",
  "Denial and error",
  "Deerts",
  "Disinspect",
  "Does a bear shit on the pope?",
  "Don't judge a cover of a book by its look",
  "Doobie-lin",
  "Do onto others as you do onto you",
  "Do you wanna get married by me?",
  "Dressed all over",
  "DVD",
  "Elemental school",
  "Escape goat",
  "Ever never again",
  "Every kid goes through phrases",
  "False Acriminations",
  "Fenis",
  "Fire Retarded",
  "Fill my feet",
  "Finders Creepers",
  "Five-minute rule",
  "For the Gooder of Us All",
  "Forward-Fast",
  "Frog",
  "Frustated",
  "FuckEx",
  "Friends with the Benedicts",
  "Flames were golfing",
  "Flying things",
  "Fuck the fuck off",
  "Get related",
  "Get Bornt",
  "Get goodin' at it",
  "Get two birds stoned at once",
  "Getting like Hank at this",
  "Golds",
  "Good things come to those at the gate",
  "Googly search",
  "Gorilla see, Gorilla do",
  "Gram son",
  "Green grapes with the crunchy things in the middle",
  "Happy hour ever after",
  "Hark attack",
  "Hair Shellac",
  "Hang your horses",
  "Heart congestion",
  "Hit 'em with everything we caught",
  "Hobolo",
  "Home trees",
  "Honesty is just a test policy",
  "Honorly system",
  "Hornse",
  "Hyposuction",
  "I do trust his judgmentals",
  "I dont have enough people words to make it understand you the way it understands me",
  "I'm an Optometrist",
  "I'm just stretched out",
  "I'm not going to put my dad in jeopardization",
  "Incubaker",
  "Indianapolis Jones",
  "Ironland",
  "It's better to have a gun and need it than to not have a gun and not need it",
  "It's clear to see who makes the pants here",
  "I-surance",
  "It doesn't take rocket appliances",
  "Juniper",
  "Keep your friends close, but your enemies toaster",
  "Get Learnt",
  "Leaves comber",
  "Lemonzine",
  "Let guy bonds be guy bonds",
  "Let's make toast",
  "Long stories get short",
  "Looks like we need two turnips and heat",
  "Lurches",
  "Magdolin",
  "Make like a tree and fuck off",
  "Make my words",
  "Man-On Man-On",
  "Marsmelons",
  "Mating name",
  "Maturinate",
  "Meat Dick(s)",
  "Mexicali Stand-on",
  "Middleland",
  "Multi-usefullness",
  "My minds started racing against each other",
  "No things attached",
  "North of-Americas",
  "Not in the right frames of the mind",
  "Nulted and void",
  "Off their leeches",
  "On slim ice",
  "One man's garbage is another man person's good ungarbage",
  "Outdoor Curckey Tucker",
  "Passed with flying fuckin' carpets",
  "Pavin' a fuckin' point",
  "Peach'n'cake",
  "People's freedom of choices & voices act",
  "Perspecticts",
  "PFD",
  "Phill Cosby",
  "Pillow berry",
  "Pick someone your own brain size",
  "Play that \"Diane Sawyer\" song",
  "Plutonium loveship",
  "Praying Atlantis",
  "Let Pylon be Pylons",
  "Razor Focused",
  "Refuckulate",
  "Reap off",
  "Responsables",
  "Rocket appliances",
  "Ron Cruise",
  "Saskatchewance",
  "Sasparilla",
  "Search warranty",
  "Selling me under the bus",
  "Sippy and Garfuckel",
  "Slidey Things",
  "Snoopy Dog",
  "Specialtilizations",
  "Split it 50/50/50",
  "Stretched out",
  "Supply and command",
  "Survival of the fitness",
  "Swallow my prize",
  "Sweet empowered chicken things",
  "Take it and leave it",
  "This deck of the woods",
  "Tempus fuck it",
  "Tropical earthquake",
  "Trying to make my heart attack?",
  "Two turnips in heat",
  "TVs With The Click-Clackers",
  "Water under the fridge",
  "Western Korea",
  "What comes around is all around",
  "Where there's smoke there's wires",
  "Vacational school",
  "Vice Principals",
  "What Julian doesn't grow won't burn him",
  "What Lucy doesn't know won't learn her",
  "What the fuck does that suppose to mean?",
  "Whole different kettle and dish",
  "Woke up on the left side of the bed",
  "Work in process",
  "Worldy Pipe",
  "Word Papers",
  "Worst case Ontario",
  "Scale from one or ten",
  "Spy for a spy",
  "Sudyfeds",
  "The more thinkings I have about it",
  "What was done was done",
  "Your Majesty",
  "Cosby, Bill, and 'Stache",
  "La La Lamp"
];

export const WhatHeMeant = [
  "A chain is only as strong as its weakest link",
  "One for all and all for one",
  "Aligator",
  "Alright, Einstein",
  "Cory & Trevor. Also called \"The Scooby Dumb Cock Brothers\" and \"Gumby & fucky-O\"",
  "I told you so",
  "Revenge of the Nerds",
  "Awkward situation",
  "Badminton",
  "Bee Salve",
  "Smart Phones/iPhone",
  "Beauty is in the eye of the beholder",
  "Bundle of joy",
  "Reading or Studying",
  "Breakfast in bed",
  "Bury the hatchet & burn the candle at both ends",
  "Brain (Ricky appears to be referring to the different areas in the brain that retain different kinds of information.)",
  "Can you give me a bit of credit?",
  "Carburetor",
  "Catch 22 situation",
  "VCR",
  "Charity",
  "Child support",
  "The Church of Jesus Christ of Latter Day Saints",
  "Civil War",
  "Looks like a hurricane/Tropical Storm blew through here",
  "Person with a fucked up looking red colour mohawk resembling a rooster head; Jacob's friend and classmate at Dartmouth Regional Vocational School had a red mohawk",
  "Come to terms with it",
  "Crock of Shit",
  "Crystal-clear",
  "Cubic zirconia",
  "Decals",
  "Delicate situation",
  "Trial and error",
  "Deer (Plurar)",
  "Disrespect",
  "'Does a bear shit in the woods?' combined with 'Is the pope Catholic?'",
  "Don't judge a book by its cover",
  "Dublin",
  "Do unto others what you would have others do unto you",
  "Will you marry me?",
  "All dressed",
  "DVS (Detroit Velvet Smooth)",
  "Elementary school",
  "Scapegoat",
  "Never again",
  "Goes through phases",
  "False accusations",
  "Fetus (mistaken for Penis)",
  "Flame retardant",
  "Fill My Shoes",
  "Finder Keepers",
  "Five-second rule",
  "For the Good of Us All",
  "Fast-Forward",
  "Fraud",
  "Frustrated",
  "FedEx",
  "Friends with benefits",
  "Engulfed in flames",
  "Birds",
  "Fuck off",
  "Becoming related to someone, in reference to Jacob Collins impregnating Trinity",
  "\"Is born\" or \"Give birth\"",
  "Get good at it",
  "Kill two birds with one stone",
  "Getting the hang of it",
  "Goals",
  "Good things come to those that wait",
  "Google search",
  "Monkey see, monkey do",
  "Grandson",
  "Grapes with seeds",
  "Happily ever after",
  "Heart attack",
  "Cooking spray (mistaken for hairspray that Ricky uses to style his hair)",
  "Hold your horses",
  "Indigestion",
  "Hit 'em with everything we've got",
  "Hobo",
  "Home free",
  "Honesty is the best policy",
  "Honor system",
  "Horse",
  "Liposuction",
  "I do trust his judgement",
  "I can't think of the right words to say",
  "I'm an Optimist",
  "I'm just stressed out",
  "I'm not going to put my dad in jeopardy",
  "Incubator",
  "Indiana Jones",
  "Ireland",
  "It's better to have a gun and not need it than to need a gun and not have it",
  "It's clear to see who wears the pants here",
  "Insurance",
  "It doesn't take rocket scientists",
  "Jupiter",
  "Keep your friends close, but your enemies closer",
  "Learn",
  "A yard rake",
  "Limousine",
  "Let bygones be bygones",
  "Let's make a toast",
  "Long story short",
  "Looks like need to turn up the heat",
  "Leeches",
  "Mandolin",
  "Make like a tree and leave",
  "Mark my words",
  "Man-on-Man",
  "Marshmallows",
  "Maiden name",
  "Mature",
  "Works in the meat department of the Freshmart; Jacob's friends and classmates at Dartmouth Regional Vocational School",
  "Mexican Standoff",
  "Middleman",
  "Multipurpose",
  "My mind started racing",
  "No strings attached",
  "North America",
  "Not in the right state of mind",
  "Null and void",
  "Off their leashes",
  "On thin ice",
  "One man's garbage is another man's treasure.",
  "Outdoor Turkey Cooker",
  "Passed with flying colours",
  "Proving a point",
  "Piece of cake/ peaches n' creme",
  "Canadian Charter of Rights and Freedoms",
  "Perspectives",
  "Ph.D",
  "Bill Cosby",
  "Pillsbury",
  "Pick on someone your own size",
  "Play that \"Tom Sawyer\" song",
  "Platonic friendship",
  "Praying mantis",
  "Let Bygones be Bygones",
  "Laser Focused",
  "Recalculate ",
  "Rip off",
  "Responsibilities",
  "Rocket science",
  "Tom Cruise",
  "Sasquatch",
  "Salmonella",
  "Search warrant",
  "Conflating \"throwing me under the bus\" and \"selling me down the river.\"",
  "Simon and Garfunkel",
  "Deejay mixing console",
  "Snoop Dogg",
  "Specialists",
  "Split it 50/50",
  "Stressed out",
  "Supply and demand",
  "Survival of the fittest",
  "Swallow my pride",
  "Sweet and Sour Chicken Wings",
  "Take it or leave it",
  "This neck of the woods",
  "Tempus fugit",
  "Tropical storm",
  "Trying to give me a heart attack?",
  "Turn up the heat",
  "Desktop computer",
  "Water under the bridge",
  "North Korea",
  "What goes around comes around",
  "Where there's smoke there's fire",
  "Vocational school",
  "Principles",
  "What Julian doesn't know won't hurt him",
  "What Lucy doesn't know won't hurt her",
  "What is that supposed to mean?",
  "Whole different kettle of fish",
  "Woke up on the wrong side of the bed",
  "Work in progress",
  "Internet",
  "Documents",
  "Worst case scenario",
  "Scale from one to ten",
  "Eye for an Eye (I spy with my little Eye)",
  "Sudafed",
  "The more I think about it",
  "What's done is done",
  "Your Honour",
  "Crosby, Stills, & Nash",
  "Lava Lamp"
];
